//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dora.ExceptionHandling.Abstractions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dora.ExceptionHandling.Abstractions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default exception policy is not set..
        /// </summary>
        internal static string ExceptionDefaultPolicyNotExists {
            get {
                return ResourceManager.GetString("ExceptionDefaultPolicyNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple exception policies for the exception type &quot;{0}&quot;..
        /// </summary>
        internal static string ExceptionDuplicateExceptionType {
            get {
                return ResourceManager.GetString("ExceptionDuplicateExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception is thrown during performing exception handling. For detailed information, please check the inner exception..
        /// </summary>
        internal static string ExceptionHandlingError {
            get {
                return ResourceManager.GetString("ExceptionHandlingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExceptionInvalidExceptionHandlerType {
            get {
                return ResourceManager.GetString("ExceptionInvalidExceptionHandlerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The excecption type &quot;{0}&quot; is not a valid replace exception type..
        /// </summary>
        internal static string ExceptionInvalidReplaceExceptionType {
            get {
                return ResourceManager.GetString("ExceptionInvalidReplaceExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The excecption type &quot;{0}&quot; is not a valid wrap exception type..
        /// </summary>
        internal static string ExceptionInvalidWrapExceptionType {
            get {
                return ResourceManager.GetString("ExceptionInvalidWrapExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified exception policy &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string ExceptionPolicyNotFound {
            get {
                return ResourceManager.GetString("ExceptionPolicyNotFound", resourceCulture);
            }
        }
    }
}
