//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dora.DynamicProxy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dora.DynamicProxy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type to intercept must be an interface..
        /// </summary>
        internal static string ExceptionArgumentNotInterface {
            get {
                return ResourceManager.GetString("ExceptionArgumentNotInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interceptor for get and set method cannot be both null..
        /// </summary>
        internal static string ExceptionGetAndSetMethodBasedInterceptorCannotBeNull {
            get {
                return ResourceManager.GetString("ExceptionGetAndSetMethodBasedInterceptorCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The get method of the property &quot;{0}&quot; of the type &quot;{1}&quot; does not exist..
        /// </summary>
        internal static string ExceptionGetMethodNotExists {
            get {
                return ResourceManager.GetString("ExceptionGetMethodNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proxy class for sealed type cannot be generated..
        /// </summary>
        internal static string ExceptionNotAllowSealedType {
            get {
                return ResourceManager.GetString("ExceptionNotAllowSealedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type to intercept must not be a sealed type..
        /// </summary>
        internal static string ExceptionSealedTypeNotAllowed {
            get {
                return ResourceManager.GetString("ExceptionSealedTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set method of the property &quot;{0}&quot; of the type &quot;{1}&quot; does not exist..
        /// </summary>
        internal static string ExceptionSetMethodNotExists {
            get {
                return ResourceManager.GetString("ExceptionSetMethodNotExists", resourceCulture);
            }
        }
    }
}
